DROP TABLE IF EXISTS "USER";
DROP TABLE IF EXISTS "DEVICES";
DROP TABLE IF EXISTS "BILLING_INFO";
DROP TABLE IF EXISTS "CATEGORY";
DROP TABLE IF EXISTS "ITEM";
DROP TABLE IF EXISTS "DEPENDENCY";
DROP INDEX IF EXISTS "DEP_IDX";
DROP TABLE IF EXISTS "ORDER";
